---
- name: Download Latest version of WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extract WordPress archive
  command: /bin/tar xzvf latest.tar.gz
  args:
    chdir: /tmp/
    creates: /tmp/wordpress

- name: Make wp directory
  file:
    path: /usr/local/openresty/nginx/html/default/
    state: directory

- name: copy wordpress directory
  shell: cp -a /tmp/wordpress/. /usr/local/openresty/nginx/html/default/
  args:
    creates: /usr/local/openresty/nginx/html/default/

- name: Fetch random salts for WordPress config
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    methond: GET
    return_content: yes
  register: wp_salt

- name: Print wp_salt
  debug:
    var: wp_salt.content

- name: "Create WordPress database {{ wp_db_name }}"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  when: wp_new_db == true

- name: Copy database {{ wp_db_name }} file
  copy:
    src: "{{ wp_db_name }}.sql.bz2"
    dest: /tmp
  when: wp_new_db == false

- name: Restore {{ wp_db_name }} database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: import
    target: /tmp/{{ wp_db_name }}.sql.bz2
  when: wp_new_db == false

- name: Create WordPress database user
  mysql_user:
    #name: "{{ wp_db_user }}"
    #password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: 'localhost'
    state: present

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: /usr/local/openresty/nginx/html/default/

- name: Change ownership of WordPress installation
  file:
    path: /srv/wordpress/
    owner: nginx
    group: nginx
    state: directory
    recurse: yes

- name: WordPress SELinux configuration
  block:
    - name: set the SELinux policy for the Wordpress directory
      sefcontext:
        target: '/srv/wordpress(/.*)?'
        setype: httpd_sys_content_t
        state: present
        reload: yes

    - name: set the SELinux policy for wp-config.php
      sefcontext:
        target: '/srv/wordpress/wp-config\.php'
        setype: httpd_sys_script_exec_t
        state: present
        reload: yes

    - name: set the SELinux policy for wp-content directory
      sefcontext:
        target: '/srv/wordpress/wp-content(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
        reload: yes

    - name: set the SELinux policy for the *.php files
      sefcontext:
        target: '/srv/wordpress/.*\.php'
        setype: httpd_sys_script_exec_t
        state: present
        reload: yes

    - name: set the SELinux policy for the Upgrade directory
      sefcontext:
        target: '/srv/wordpress/wp-content/upgrade(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
        reload: yes

    - name: set the SELinux policy for the Uploads directory
      sefcontext:
        target: '/srv/wordpress/wp-content/uploads(/.*)?'
        setype: httpd_sys_rw_content_t
        state: present
        reload: yes

    - name: set the SELinux policy for the wp-includes php files
      sefcontext:
        target: '/srv/wordpress/wp-includes/.*\.php'
        setype: httpd_sys_script_exec_t
        state: present
        reload: yes

    - name: set the SELinux on all the Files
      command: restorecon -Rv /srv/wordpress

  when: sel_disable == false

- name: restart php71-php-fpm
  service:
    name: php71-php-fpm
    state: restarted
  ignore_errors: true
