---
  # Task to install and configure WordPress
  # TODO:
  # 1.) TESTING OF Installation of Nginx Helper Plugin: https://wordpress.org/plugins/nginx-helper/

- name: Download Latest version of WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extract WordPress archive
  command: /bin/tar xzvf latest.tar.gz
  args:
    chdir: /tmp/
    creates: /tmp/wordpress

- name: Make wordpress directory
  file:
    path: "{{ resty_default_web_dir }}/"
    state: directory

- name: copy wordpress files
  shell: cp -a /tmp/wordpress/. {{ resty_default_web_dir }}/
  args:
    creates: "{{ resty_default_web_dir }}/license.txt"

- name: Fetch random salts for WordPress config
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    methond: GET
    return_content: yes
  register: wp_salt

- name: Print wp_salt
  debug:
    var: wp_salt.content

- name: "Create WordPress database {{ wp_db_name }}"
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
  when: wp_new_db == true

- name: Copy database {{ wp_db_name }} file
  copy:
    src: "{{ wp_db_name }}.sql.bz2"
    dest: /tmp
  when: wp_new_db == false

- name: Restore {{ wp_db_name }} database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: import
    target: /tmp/{{ wp_db_name }}.sql.bz2
  when: wp_new_db == false

- name: Create WordPress database user
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: 'localhost'
    state: present

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: "{{ resty_default_web_dir }}/"

- name: Change ownership of WordPress installation
  file:
    path: "{{ resty_default_web_dir }}/"
    owner: nginx
    group: nginx
    state: directory
    recurse: yes

- name: WordPress SELinux configuration
  include_tasks: selinux.yml
  when: sel_disable == false

- name: Install Nginx Helper plugin
  unarchive:
    src: https://downloads.wordpress.org/plugin/nginx-helper.1.9.10.zip
    dest: "{{ resty_default_web_dir }}/wp-content/plugins/"
    creates: /usr/local/openresty/nginx/html/default/wp-content/plugins/nginx-helper/readme.txt
    remote_src: yes

- name: restart php71-php-fpm
  service:
    name: php71-php-fpm
    state: restarted
  ignore_errors: true
