# @Author: Haupt Joshua <HauptJ>
# @Date:   26-Mar-2018
# @Email:  josh@hauptj.com
# @Filename: main.yml
# @Last modified by:   HauptJ
# @Last modified time: 02-Apr-2018

---
  # Task to install and configure WordPress

- name: Download Latest version of WordPress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/latest.tar.gz

- name: Extract WordPress archive
  command: /bin/tar xzvf latest.tar.gz
  args:
    chdir: /tmp/
    creates: /tmp/wordpress

- name: Make wordpress directory
  file:
    path: "{{ resty_default_web_dir }}/"
    state: directory

- name: copy wordpress files
  shell: cp -a /tmp/wordpress/. {{ resty_default_web_dir }}/
  args:
    creates: "{{ resty_default_web_dir }}/license.txt"

- name: Fetch random salts for WordPress config
  uri:
    url: https://api.wordpress.org/secret-key/1.1/salt/
    methond: GET
    return_content: yes
  register: wp_salt

- name: Print wp_salt
  debug:
    var: wp_salt.content

# NOTE: WordPress database tasks have been moved to ansible-role-mariadb

- name: Copy WordPress config file
  template:
    src: wp-config.php
    dest: "{{ resty_default_web_dir }}/"

- name: Change ownership of WordPress installation
  file:
    path: "{{ resty_default_web_dir }}/"
    owner: nginx
    group: nginx
    state: directory
    recurse: yes

- name: WordPress SELinux configuration
  include_tasks: selinux.yml
  when: sel_disable == false

- name: Install WordPress Plugins
  unarchive:
    src: https://downloads.wordpress.org/plugin/{{ item.name }}.{{ item.ver }}.zip
    dest: "{{ resty_default_web_dir }}/wp-content/plugins/"
    creates: /usr/local/openresty/nginx/html/default/wp-content/plugins/{{ item.name }}/readme.txt
    remote_src: yes
  with_items:
    - { name: nginx-helper, ver: 1.9.11 }
    - { name: wordpress-importer, ver: 0.6.4 }
    - { name: do-spaces-sync, ver: 1.1.1 }

- name: Install WordPress Themes
  unarchive:
    src: https://downloads.wordpress.org/theme/{{ item.name }}.{{ item.ver }}.zip
    dest: "{{ resty_default_web_dir }}/wp-content/themes/"
    creates: /usr/local/openresty/nginx/html/default/wp-content/themes/{{ item.name }}/readme.txt
    remote_src: yes
  with_items:
    - { name: bhari, ver: 1.0.4.9 }

- name: Push uploads
  synchronize:
    mode: push
    dest: "{{ resty_default_web_dir }}/wp-content/uploads/"
    src: "{{ wp_uploads_backup_dir }}/"
    recursive: yes
  delegate_to: localhost

- name: restart php71-php-fpm
  service:
    name: php71-php-fpm
    state: restarted
  ignore_errors: true
